richMachine/API/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from .views.api_casino import GenerateCombinationView
from .views.api_house import (BuyHouseView, CreateBasementView,
                              GetBalanceBasementView, GetBasementView,
                              GetHouseView, GetMyHousesView,
                              GetTakeProfitBasementView, SellHouseView,
                              UpgradeBasementView)
from .views.api_jobs import WorkAPI
from .views.api_items import GetItem, BuyItem
from .views.api_other import GetInventory, GetSymbolCrypt
from .views.api_transport import (BuyTransportView, CheckTransportInfo,
                                  GetMyCarsView, GetMyYachtsView,
                                  SellTransportToState, SellTransportToPlayer)
from .views.api_users import (ChangeLanguageView, ChangeNicknameView,
                              GetBalance, ProfileView)

from .views.api_login import LoginView, LogoutUserView, loguot_user
from .views.api_register import RegistrationView

app_name = 'api'

urlpatterns = [
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    path('change_nickname/', ChangeNicknameView.as_view(), name='change_nickname'),
    path('change_language/', ChangeLanguageView.as_view(), name='change_language'),
    path('get_profile/', ProfileView.as_view(), name='get_profile'),
    
    # Property views
    path('get_my_cars/', GetMyCarsView.as_view(), name='get_my_cars'),
    path('get_my_yachts/', GetMyYachtsView.as_view(), name='get_my_yachts'),
    path('get_my_houses/', GetMyHousesView.as_view(), name='get_my_houses'),
    path('get_house/<int:id_house>/', GetHouseView.as_view(), name='get_house'),
    path('get_basement/<int:id_house>/', GetBasementView.as_view(), name='get_basement'),
    path('take_profit_basement/', GetTakeProfitBasementView.as_view(), name='take_profit_basement'),
    path('sell_house/<int:id>/', SellHouseView.as_view(), name='sell_house'),
    path('create_basement/', CreateBasementView.as_view(), name='create_basement'),
    path('upgrade_basement/<int:id_house>/', UpgradeBasementView.as_view(), name='upgrade_basement'),
    path('get_balance_basement/<int:id_house>/', GetBalanceBasementView.as_view(), name='get_balance_basement'),
    path('sell_transport_to_player/', SellTransportToPlayer.as_view(), name='sell_transport_to_player'),
    
    path('buy_transport/', BuyTransportView.as_view(), name='buy_transport'),
    path('buy_house/', BuyHouseView.as_view(), name='buy_house'),
    path('buy_item/', BuyItem.as_view(), name='buy_item'),
    
    # Banking
    path('get_balance/', GetBalance.as_view(), name='get_balance'),
    path('transport_info/', CheckTransportInfo.as_view(), name='transport_info'),
    path('sell_transport_to_state/<str:type>/<str:ucode>/', SellTransportToState.as_view(), name='sell_transport_to_state'),
    path('symbol_crypt/', GetSymbolCrypt.as_view(), name='get_symbol_crypt'),
    
    # Other
    path('get_inventory/', GetInventory.as_view(), name='get_inventory'),
    path('slot/generate/', GenerateCombinationView.as_view()),
    path('item/', GetItem.as_view(), name='get_item'),

    # Jobs
    path('update_clicks/', WorkAPI.as_view(), name='upd_clicks'),


    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', loguot_user, name='logout'),
    # House functions
    # path('house/change_class/', ChangeClassHouse.as_view(), name='change_class')
]

richMachine/homePage/urls.py
from django.urls import path
from . import views

app_name = 'homePage'

urlpatterns = [
    path('', views.index, name='home'),
    # path('profile/<str:username>/', views.profile, name='profile'),
]

richMachine/users/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.contrib.auth.views import PasswordChangeView

from . import views

app_name = 'users'

# handler400 = 'users.views.bad_request'
# handler403 = 'users.views.permission_denied'
handler404 = 'users.views.page_not_found'
# handler500 = 'users.views.server_error'

urlpatterns = [
    path('register/', views.SignUpView.as_view(), name='register'),
    # path('profile/<int:server_id>/', views.profile, name='profile'),
    # path('profile/', views.self_profile, name='self_profile'),
    # path('change_nickname/', views.change_nickname, name='change_nickname'),
    # path('change_language/', views.change_language, name='language'),
    path('login/', views.SignInView.as_view(), name='login'),
    # path('logout/', views.loguot_user, name='logout'),
    # path('password_change/',
    #      PasswordChangeView.as_view(template_name='registration/password_change.html'),
    #      name='password_change'),
    # path('sell_transport/<str:type>/<str:ucode>/', views.sell_transport, name='sell_transport'),
    # path('get_transport_profile/<str:type>/<str:ucode>/', views.get_transport_profile, name='get_transport_profile'),
    # path('get_house_profile/<int:id>/', views.get_house_profile, name='get_house_profile'),
    # path('sell_house/<int:id>/', views.sell_house, name='sell_house'),

    # path('telegram/', views.accept, name='accept'),
]

richMachine/homePage/views.py
from django.shortcuts import render
from icecream import ic
from django.core.handlers.wsgi import WSGIRequest


# Create your views here.
def index(request: WSGIRequest):

    data = {
        'title': "Rich Machine",
        'username': request.user.username,
        "my_server_id": request.user.server_id if not request.user.is_anonymous else False
    }
    return render(request, 'homePage/index.html', data)

richMachine/homePage/templates/homePage/layout.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" href="{% static 'homePage/img/logo.png' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&family=Cinzel:wght@400..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Moul&display=swap" rel="stylesheet">

    <link href="{% sass_src 'homePage/styles/layout.scss' %}" rel="stylesheet" type="text/css">
{#    <link rel="stylesheet" href="{% static 'homePage/styles/style.css' %}">#}
    {% block stylesheet %} {% endblock %}



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'homePage/js/index.js' %}" defer></script>
    {% block script %}
    {% endblock %}

</head>

<body>
    <div class="container">
        <header class="a_cap">
            <div class="header__logo">
                <a href="{% url 'homePage:home' %}">
                    <img class="logo__icon" src="{% static 'homePage/img/logo.svg' %}">
                </a>
                <div class="logo__text">Rich<br>Machine</div>
            </div>
            <ul class="header__buttons">
                {% if my_server_id %}
                    <li><a href="/profile/" class="header__button">Профиль</a></li>
                    {% csrf_token %}
                    <li><a href="#" class="header__button" id="logout-button">Выйти</a></li>
                {% else %}
                    <li><a href="/users/login/" class="header__button">Войти</a></li>
                {% endif %}
                <li><a href="/magazine" class="header__button">Магазин</a></li>
                <li>
                    <select id="functions" name="fruits" class="header__button" onchange="navigateToPage()">
                        <option class="bckgd-func" style="color: #7d7d7d" value="">Выберите</option>
                        <option class="bckgd-func" value="/donate">Донат</option>
                        <option class="bckgd-func" value="/casino">Казино</option>
                        <option class="bckgd-func" value="/jobs">Работа</option>
                        <option class="bckgd-func" value="/property">Имущество</option>
                        <option class="bckgd-func" value="/car_plate">Номер</option>
                        <option class="bckgd-func" value="/inventory">Инвентарь</option>
                        <option class="bckgd-func" value="/stock">Биржа</option>
                        {% if is_staff %}
                            <option class="bckgd-func admin" value="admin-panel" id="admin-panel">Админ панель</option>
{#                            <div class="bckgd-func admin"><a href="/admin-panel" id="admin-panel">Админ панель</a></div>#}
                        {% endif %}
                    </select>
                <script>
                    function navigateToPage() {
                        var select = document.getElementById("functions");
                        var url = select.value;

                        if (url) {
                            window.location.href = url; // Перенаправление на выбранную страницу
                        }
                    }
                </script>
                </li>

            </ul>
        </header>
        <div id="main">
            {% block content %}
            {% endblock %}
        </div>
        <div id="messages-container">
            <script>
                let reconnectAttempts = 0;
                const maxReconnectAttempts = 5;
                const reconnectInterval = 1000; // Интервал повторного подключения в миллисекундах

                function handleMessages(message) {
    const container = $('#messages-container');

    const parts = message.split('|');
    const alertClass = 'alert-' + 3; // Замените '3' на нужный уровень, если требуется
    let alert = $('<div class="alert ' + alertClass + '"></div>');

    if (parts.length > 1) {
        alert.append('<strong>' + parts[0] + '</strong><br>' + parts[1]);
    } else {
        alert.text(message);
    }

    // Проверяем количество уведомлений в контейнере
    const currentAlerts = container.children('.alert');

    if (currentAlerts.length >= 4) {
        // Удаляем самое старое уведомление
        currentAlerts.last().addClass('slide-out'); // Добавляем класс для анимации
        setTimeout(() => {
            currentAlerts.last().remove(); // Удаляем элемент после завершения анимации
        }, 500); // Длительность анимации
    }

    // Добавляем уведомление в контейнер и анимируем его появление
    container.prepend(alert);
    alert.hide().fadeIn(300); // Скрываем уведомление сначала и затем плавно показываем

    setTimeout(() => {
        alert.addClass('slide-out'); // Добавляем класс для анимации исчезновения
        setTimeout(() => {
            alert.remove(); // Удаляем элемент после завершения анимации
        }, 500); // Длительность анимации
    }, 5000);
}


                function fConnect() {
                    const socket = new WebSocket(`ws://${location.host}/ws/notifications/`);

                    socket.onopen = function() {
                        console.log('Соединение установлено');
                        reconnectAttempts = 0; // Сбрасываем счетчик при успешном подключении
                    };

                    socket.onmessage = function(event) {
                        const data = JSON.parse(event.data);
                        handleMessages(data.text);
                    };

                    socket.onclose = function(event) {
                        console.log('Соединение закрыто, код:', event.code);
                        console.log(`Попытка переподключения`);
                        setTimeout(fConnect, reconnectInterval);
                    };

                    socket.onerror = function(error) {
                        socket.close(); // Закрываем соединение при ошибке
                    };
                }

                // Запускаем подключение при загрузке страницы
                fConnect();

            </script>
        </div>
    </div>
</body>

richMachine/homePage/templates/homePage/profile.html
{% extends 'homePage/layout.html' %}
{% load static %}
{% load humanize %}
{% load my_filters %}
{% block title %} {{title}} {% endblock %}
{% block username %}{{ username }}{% endblock %}
{% block server_id %}{{ server_id }}{% endblock %}

{% block stylesheet %} 
<link rel="icon" href="{% static 'homePage/img/logo.png' %}">


<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<link href="https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@400;700;900&family=Cinzel:wght@400..900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Moul&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'homePage/styles/style_profile.css' %}">
{% endblock %}


{% block script %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'homePage/js/profile.js' %}" defer></script>
{% endblock %}



{% block content %}

<div class="main-info">
    <div class="info">
        <div class="up">
            <div class="nickname" id="nickname">
                {% if server_id == my_server_id %}
                    <span class="edited" style="cursor: pointer" id="current-name">{{ nickname.name }}</span>
                {% else %}
                    <span class="static" id="current-name">{{ nickname.name }}</span>
                {% endif %}

                {% if language == 'ru' %}
                    <img src="{% static 'homePage/img/russia.svg' %}" />
                {% else %}
                    <img src="{% static 'homePage/img/eng.svg' %}" />
                {% endif %}
                <br>
                <span class="job-name">{{ job.title }}</span>
            </div>
            <div id="nicknameModal" class="modal">
                <div class="modal-content">
                  <form id="nickname-form" method="POST" action="{% url 'users:change_nickname' %}">
                    {% csrf_token %}
                    <label for="new_nickname" class="label_new_nickname">Введите новый никнейм</label>
                    <input type="text" id="new_nickname" name="new_nickname" placeholder="Никнейм" required>
                    <div class="buttons">
                      <button type="button" id="close_nickname">Закрыть</button>
                      <button type="reset" id="accept_nickname">Подтвердить</button>
                    </div>
                  </form>
                </div>
            </div>
            
            {% if server_id == my_server_id %}
                <div class="donate-coin">
                    <span>{{ donate_balance|intcomma }} DC</span>
                </div>
            {% else %}
                <div class="donate-coin" style="visibility: hidden;">
                    <span>{{ donate_balance|intcomma }} DC</span>
                </div>
            {% endif %}
            
            
              

        </div>
        <div class="down">
            <div class="info-group">
                <div class="balance">
                    <div class="balance__cash nowrap">Наличные: {{money.cash|intcomma}} ₽</div>
                    <br>
                    <div class="balance__bank nowrap">Банк: {{money.bank|intcomma}} ₽</div>
                </div>
                <div class="couple">
                    {% if couple.user_id %}
                        <div class="couple__username nowrap">Супруг(а) Лерка</div>
                        <br>
                        <div class="couple__date nowrap">В браке с 04.01.2023</div>
                    {% else %}
                        <div class="couple__username nowrap">Супруг(а) не найден</div>
                        <!-- <br>
                        <div class="couple__date nowrap" style="visibility: hidden;">a</div> -->
                    {% endif %}
                </div>
            </div>
            <div class="dollar">
                <img src="{% static 'homePage/img/profile_dollar.svg' %}"/>
            </div>
        </div>
    </div>
</div>

<div class="property">
    <div class="cars">
        <span class="type-property">Автомобили</span>

        {% for car in car.cars %}
            <div class="car frosted_glass" id="{{car.id}}">
                <span class="car__name">{{car.name}}</span><br>
                <span class="car__price">Гос.стоимость - {{car.price|intcomma}} ₽</span>
            </div>
        {% endfor %}
    </div>
    <div class="yachts">
        <span class="type-property">Яхты</span>
        {% for yacht in yacht.yachts %}
            <div class="yacht frosted_glass" id="{{yacht.id}}">
                <span class="yacht__name">{{yacht.name}}</span><br>
                <span class="yacht__price">Гос.стоимость - {{yacht.price|intcomma}} ₽</span>
            </div>
        {% endfor %}
    </div>
    <div class="houses">
        <span class="type-property">Недвижимость</span>
        {% for house in houses %}
            <div class="house frosted_glass" id="{{house.id}}">
                <span class="house__name">{{house.district_info.name|translite}} {{house.type}} №{{house.id}}</span><br>
                <span class="house__price">Гос.стоимость - {{house.price|intcomma}} ₽</span>
            </div>
        {% endfor %}
    </div>
</div>



<span class="sun">
    
</span>
{% endblock %}